config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do 
    resources :todo_lists
      resources :items, only: [:create, :update, :destroy]
  end 
  
  
  get 'items/index'

  resources :todo_lists do 
    resources :items  
  end 
  
  root "todo_lists#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :todo_list
  validates :content, presence: true, length: { minimum: 2 } 
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :items
  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :find_todo_list
  
  def create
    @item = @todo_list.items.new(item_params)
    if @item.save 
      render json: {
        status: 200,
        messeage: "Sucessfully created item.",
        todo_list: @item
      }.to_json 
        
    else
      render json: { status: 422, message: "Error creating item", todo_list: @item }.to_json
    end
  end


  private 
   
  def item_params
     params.require(:todo_list).permit(:title, :description)
  end 
   
  def find_todo_list 
    @todo_list = TodoList.find(params[:todo_list_id])
  end 

end 

app/controllers/api/todo_lists_controller.rb
class Api::TodoListsController < ApplicationController 
  
  skip_before_filter :verify_authenticity_token
  
  def index
    @todo_lists = TodoList.all
    render json: @todo_lists
  end 
  
  def shows
    @todo_list = TodoList.find(params[:id])
    respond_to do |format|
      format.json { render :json => @todo_list }
    end 
  end 
  
  def new 
    @todo_list = TodoList.new 
  end 
  
  def create
    @todo_list = TodoList.new(todo_list_params)
    if @todo_list.save 
      render json: {
        status: 200,
        messeage: "Sucessfully created Todo list.",
        todo_list: @todo_list
      }.to_json 
        
    else
      render json: { status: 422, message: "Error creating Todo list", todo_list: @todo_list }.to_json
    end
  end 
  
  def edit 
    @todo_list = Todolist.find(params[:id])
  end 
  
  def update 
    @todo_list = TodoList.find
    if @todo_list.update(todo_list_params)
      render json: { status: 200, message: "Sucessfully updated Todo list", todo_list: @todo_list }.to_json
    else 
      render json: { status: 422, message: "Error updating Todo list", todo_list: @todo_list }.to_json
    end 
  end 
  
  def destroy 
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy 
    render json: {
        status: 200,
        messeage: "Sucessfully destroyed Todo list.",
        todo_list: @todo_list
      }.to_json
  end 
   
   private 
   
   def todo_list_params
     params.require(:todo_list).permit(:title, :description)
   end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 
  #before_action :set_item, only: [:index, :new, :create, :edit, :update]
 
  
  def index
    #binding.pry
    @todo_list = TodoList.find(params[:todo_list_id])
  end
  
  def show 
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = @todo_list.items.find(params[:id])
  end 
  
  def new 
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = @todo_list.items.build
  end 
  
  def create 
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = @todo_list.items.build(item_params)
    if @item.save 
      flash[:success] = "Your item has been created succesfully"
      redirect_to todo_list_items_path(@todo_list)
    else 
      flash.now[:error] = "Something went wrong with your form"
      render :new
    end 
  end 
  
  def edit 
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = @todo_list.items.find(params[:id])
  end 
  
  def update
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = @todo_list.items.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Your item has been udpated"
      redirect_to todo_list_items_path
    else 
      flash.now[:error] = "Your item failed to update"
      render :edit 
    end 
  end 
  
  def destroy
    @todo_list = TodoList.find(params[:todo_list_id])
    @item = @todo_list.items.find(params[:id])
    @item.destroy 
    flash[:success] = "Your item has been succesfully deleted"
    redirect_to todo_list_items_path(@todo_list)
  end 
  
  private 
  
    def item_params
      params.require(:item).permit(:todo_list_id, :content, :status, :id)
    end
    
    #def set_item
      # @todo_list = TodoList.find(params[:todo_list_id])
       #@item = @todo_list.items.find(params[:id])
    #end 
    

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/items/edit.html.erb
<h1> Edit </h1>

<%= form_for [@todo_list, @item] do |form| %>
  <p> 
    <%= form.label :content %>
    <%= form.text_field :content %>
  </p>
  
  <p>
    <%= form.label :status %>
    <%= form.check_box :status %>
  </p>
  
  <p>
    <%= form.submit "Save" %> 
  </p>
<% end %>

app/views/items/index.html.erb
<h1><%= @todo_list.title %></h1>
<p>Find me in app/views/items/index.html.erb</p>

<ul class="items">
  <% @todo_list.items.each do |item| %>
    <li> <%= item.content %> 
    | <%= link_to "Edit", edit_todo_list_item_path(@todo_list, item) %> 
    | <%= link_to "Delete", todo_list_item_path(@todo_list, item), method: :delete, data: { confirm: 'Are you sure?' } %>
    | <%= link_to "Show", todo_list_item_path(@todo_list, item) %>
    </li>
  
  <% end %>
</ul>

<p>
  <%= link_to "New todo item", new_todo_list_item_path %>
</p>

app/views/items/new.html.erb
<%= form_for [@todo_list, @item] do |form| %>

 <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p> 
    <%= form.label :content %>
    <%= form.text_field :content %>
  </p>
  
  <p>
    <%= form.label :status %>
    <%= form.check_box :status %>
  </p>
  
  <p>
    <%= form.submit "Save" %> 
  </p>
  
  
<% end %>

app/views/items/show.html.erb
<h1> Todo List Item </h1>

<p> 
  content: <%= @item.content %>
</p>

<p>
  status: <%= @item.status %> 
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItemManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
    <div class="alert flash <%= type %>">
       <%= message %> 
    </div>
  <% end %> 

<%= yield %>

</body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr id="<%= dom_id(todo_list) %>">
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to "List items", todo_list_items_path(todo_list) %> </td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>